### ISSUE TITLE
Is it still working?

### ISSUE THREAD

**Issue by Insomnia731** [DedInc/freetempmail#1]
Hi! Is it still working?
This error appears on startup:

> Traceback (most recent call last):
File "mal1.py", line 5, in <module>
email = ft.getEmail() #returns email
File "/usr/local/lib/python3.10/dist-packages/freetempmail/freetempmail.py", line 52, in getEmail
return s.get('https://web2.temp-mail.org/mailbox', headers=authHeaders).json()['mailbox']
NameError: name 's' is not defined

**Comment by DedInc** [comment]
fixed
